//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipWebsite.UacService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UacService.IUac")]
    public interface IUac {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUac/DoWork", ReplyAction="http://tempuri.org/IUac/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUac/DoWork", ReplyAction="http://tempuri.org/IUac/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUac/DoMoreWork", ReplyAction="http://tempuri.org/IUac/DoMoreWorkResponse")]
        string DoMoreWork(string pString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUac/DoMoreWork", ReplyAction="http://tempuri.org/IUac/DoMoreWorkResponse")]
        System.Threading.Tasks.Task<string> DoMoreWorkAsync(string pString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUacChannel : ParsnipWebsite.UacService.IUac, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UacClient : System.ServiceModel.ClientBase<ParsnipWebsite.UacService.IUac>, ParsnipWebsite.UacService.IUac {
        
        public UacClient() {
        }
        
        public UacClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UacClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UacClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string DoMoreWork(string pString) {
            return base.Channel.DoMoreWork(pString);
        }
        
        public System.Threading.Tasks.Task<string> DoMoreWorkAsync(string pString) {
            return base.Channel.DoMoreWorkAsync(pString);
        }
    }
}
