//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Albums
    {
        public System.Guid id { get; set; }
        public System.Guid createdbyid { get; set; }
        public System.DateTime datecreated { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
