//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_LogEntries
    {
        public System.Guid id { get; set; }
        public System.Guid logId { get; set; }
        public string sessionId { get; set; }
        public System.DateTime dateTime { get; set; }
        public string type { get; set; }
        public string text { get; set; }
    }
}
