//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PollOptions
    {
        public System.Guid id { get; set; }
        public System.Guid pollId { get; set; }
        public System.Guid createdByUserId { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string value { get; set; }
    }
}
