//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Requests
    {
        public System.Guid id { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid requestedByUserId { get; set; }
        public System.Guid requestSubjectUserId { get; set; }
    }
}
