//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Users
    {
        public System.Guid id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string forename { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string postCode { get; set; }
        public string mobilePhone { get; set; }
        public string homePhone { get; set; }
        public string workPhone { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> lastLogIn { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string ProfilePicUrl { get; set; }
    }
}
