//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsnipApiDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParsnipTestDbEntities : DbContext
    {
        public ParsnipTestDbEntities()
            : base("name=ParsnipTestDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Albums> t_Albums { get; set; }
        public virtual DbSet<t_Comments> t_Comments { get; set; }
        public virtual DbSet<t_ImageAlbumPairs> t_ImageAlbumPairs { get; set; }
        public virtual DbSet<t_Images> t_Images { get; set; }
        public virtual DbSet<t_LogEntries> t_LogEntries { get; set; }
        public virtual DbSet<t_Logs> t_Logs { get; set; }
        public virtual DbSet<t_PollOptions> t_PollOptions { get; set; }
        public virtual DbSet<t_Polls> t_Polls { get; set; }
        public virtual DbSet<t_Posts> t_Posts { get; set; }
        public virtual DbSet<t_Requests> t_Requests { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
    }
}
